### ISSUE TITLE
data数据？

### ISSUE THREAD

**Issue by kaigelee** [Trustworthy-AI-Group/TransferAttack#18]
想问一下，如何证明data数据被所选的网络预测正确呢？
我的方法: 直接对data数据进行eval测试，网络的攻击成功率应该是0？因为全部预测正确。但是得到的结果不为0啊？

**Comment by kaigelee** [comment]
> 想问一下，如何证明data数据被所选的网络预测正确呢？ 我的方法: 直接对data数据进行eval测试，网络的攻击成功率应该是0？因为全部预测正确。但是得到的结果不为0啊？

是否证明选的data数据有问题呢？

**Comment by xiaosen-wang** [comment]
目前data是在之前版本采用的model来选择的，更新了model zoo之后没有更新，我们近期会重新更新一组数据，感谢你的提醒。另外，由于目前选择的model比较多，所以在evaluation set当中可能部分类别找不到所有model都分类正确的图片，所以我们会选取尽可能多model分类正确的图片，这种情况下可能无法做到所有model都100%分类正确。

**Comment by kaigelee** [comment]
> 目前data是在之前版本采用的model来选择的，更新了model zoo之后没有更新，我们近期会重新更新一组数据，感谢你的提醒。另外，由于目前选择的model比较多，所以在evaluation set当中可能部分类别找不到所有model都分类正确的图片，所以我们会选取尽可能多model分类正确的图片，这种情况下可能无法做到所有model都100%分类正确。

想问一下重新更新的数据保证了目前github中eval的8种网络均可以正确预测吗？因为想要基于您的库做研究，希望能得到您的最新数据！感激不尽！
如果可能，可以加联系方式吗：
VX: 15621018185
北航 李同学

**Comment by xiaosen-wang** [comment]
最新的数据已经更新，目前可以全部分类正确
