### ISSUE TITLE
About LPM method

### ISSUE THREAD

**Issue by kaigelee** [Trustworthy-AI-Group/TransferAttack#50]
请问
![微信图片_20240514113056](https://github.com/Trustworthy-AI-Group/TransferAttack/assets/88812684/63fb1ca2-07c3-4349-8a69-c729d9c18a22)
出现运行错误，如何解决？

**Comment by kaigelee** [comment]
@xiaosen-wang @LinQinLiang

**Comment by xiaosen-wang** [comment]
We have addressed this issue and updated the code.
