### ISSUE TITLE
I would like to ask whether the code of BSR and Admix method is consistent with the description in the paper.

### ISSUE THREAD

**Issue by renxujie0926** [Trustworthy-AI-Group/TransferAttack#59]
I would like to ask whether the code of BSR and Admix method is consistent with the description in the paper. For example, in the code of BSR，I did not see the part of rotation operation for blocks mentioned in the paper. Also, I am confused about the Admix code "return torch.concat([admix_images / (2 ** i) for i in range(self.num_scale)])", is it scaling the blended image? I follow the given code and get the result is changing the brightness of the image. Thank you for your answer.
``

**Comment by xiaosen-wang** [comment]
+ For admix, it is consistent with the Eq.  (3) in the paper.

+ For BSR, we accidentally omit the rotation and will add it soon. 

Thanks for your careful check!
