### ISSUE TITLE
关于 L2T 的结果以及一些论文链接上的问题

### ISSUE THREAD

**Issue by the-full** [Trustworthy-AI-Group/TransferAttack#60]
您好！首先表达一下感谢，这个仓库的存在帮我节省了不少跑代码和查文献的时间。然后是我的问题，我在尝试复现 L2T 的结果时发现 TransferAttack 上的评估结果和其开源的[仓库](https://github.com/RongyiZhu/L2T/tree/main)上的评估结果在 cnn 模型上有明显差异（单卡， batchsize=2 下测试），具体结果如下：
| 模型名称                     |  ASR in TransferAttack (%) |  ASR in L2T |
|-------------------------|------------------------------|--------------------------|
| resnet18                      | 100.0  |  100.0 | 
| resnet101                    | 87.7   | 96.2 | 
| resnext50_32x4d         | 89.7   | 97.2 |
| denssenet121              | 98.8   | 98.4 |
| vit_base_patch16_224  | 51.4   | 48.2 |
| pit_b_224                      | 64.7   | 64.0  |
| visformer_small             | 80.0   |  78.0 |
| swin_tiny_patch4_window7_224 | 82.5  | 80.4 |

我注意到 L2T 的代码[这里](https://github.com/RongyiZhu/L2T/blob/main/utils.py#L32-L33)，和 TransferAttack 的[这里](https://github.com/Trustworthy-AI-Group/TransferAttack/blob/main/transferattack/utils.py#L29-L30) 对 cnn 模型权重设置不同，将其设置为 DEFAULT 后的结果为：
| 模型名称                     |  ASR under DEFAULT (%) | 
|-------------------------|----------------------------|
| resnet18                       | 100.0  | 
| resnet101                     | 87.6   |
| resnext50_32x4d          | 88.6   |
| denssenet121               | 98.4   |
| vit_base_patch16_224   | 48.2   |
| pit_b_224                      | 64.0   |
| visformer_small             | 80.4   | 
| swin_tiny_patch4_window7_224 | 82.5  |

我想 README 中所报告的结果可能需要更新一下，另外还应该补充一下这篇论文的链接 https://arxiv.org/abs/2405.14077 。此外，在 ir.py 的[这里](https://github.com/Trustworthy-AI-Group/TransferAttack/blob/main/transferattack/advanced_objective/ir.py#L94)给的链接是一篇差分隐私的论文，我想正确的链接应该是这个：https://arxiv.org//abs/2009.11729

**Comment by xiaosen-wang** [comment]
Thank you for pointing out the mistakes. We have updated the L2T's results and IR's link. Also, we find that there might be other wrong URLs and will check all the URLs.
