### ISSUE TITLE
about the cuda memory

### ISSUE THREAD

**Issue by Truman168** [Trustworthy-AI-Group/TransferAttack#74]
你好，我想问一下，就是我把surrogate model换成inceptionv3之后，在运行时，显存不断增加，最后直接爆掉了(总共有24G显存)，batchsize也改小了，我想问下这是怎么回事呀，是因为RAP这个方法需要很大的显存吗

**Comment by xiaosen-wang** [comment]
We have changed the code and you can try it again.

**Comment by Truman168** [comment]
> We have changed the code and you can try it again.

thanks very much！！！

**Comment by lazylittlezhao** [comment]
May I ask what the cause is? I am experiencing the same thing with other methods and other models, can you please advise what is causing it so I can modify it in order to run it. Thanks a lot!
