### ISSUE TITLE
ghost Networks

### ISSUE THREAD

**Issue by wanqiang512** [Trustworthy-AI-Group/TransferAttack#8]
作者您好
请问这篇论文的pytorch的代码能实现到存储库吗？ 非常感谢！
1. Learning Transferable Adversarial Examples via Ghost Networks（ https://arxiv.org/abs/1812.03413 ）

**Comment by xiaosen-wang** [comment]
感谢你的关注，ghost network这篇我们已经实现了，在做最终的check，近期会release出来。
