### ISSUE TITLE
Inquiry About PyTorch 2.4.0 Support

### ISSUE THREAD

**Issue by songyuc** [Trustworthy-AI-Group/TransferAttack#82]
Dear TransferAttack Team,

I hope this message finds you well. I am a student currently exploring your framework for boosting adversarial transferability in image classification. I wanted to inquire whether TransferAttack is compatible with PyTorch 2.4.0.

If not, are there any plans to support this version in the future? 

Thank you for your assistance!

Best regards.

**Comment by Zhijin-Ge** [comment]
Hi, thanks for your interest in our work. We have tested TransferAttack on Torch=2.4.1 (CUDA=11.8), and it is compatible with Torch 2.4.1! Also, I suggest that the version of [Pytorch](https://pytorch.org/get-started/previous-versions/) should be adapted to the CUDA version to avoid unexpected errors!

**Comment by songyuc** [comment]
Thanks sincerely for your help!

**Comment by songyuc** [comment]
Thanks sincerely for you help!

**Comment by zqyjww** [comment]
May I ask if I can try to generate adversarial samples using ResNet50 or ResNet152 as proxy models? For example, Python main. py -- input_ir/ path/to/data --output_dir adv_data/logit/resnet18_targeted --attack logit --model=resnet50 --targeted

**Comment by Zhijin-Ge** [comment]
> May I ask if I can try to generate adversarial samples using ResNet50 or ResNet152 as proxy models? For example, Python main. py -- input_ir/ path/to/data --output_dir adv_data/logit/resnet18_targeted --attack logit --model=resnet50 --targeted

For most of the methods in this repository, you can just replace the proxy model to run them. It should be noted that there are some papers where the authors have fine-tuned or re-trained a particular proxy model, and this time you need to follow the model provided by the author for the attack. We suggest that you need to consider whether you can replace it based on the original paper.
