### ISSUE TITLE
论文MIG方法代码中的一点问题

### ISSUE THREAD

**Issue by lzclzclzc12** [Trustworthy-AI-Group/TransferAttack#91]
![MIG](https://github.com/user-attachments/assets/10470cdb-847f-49d0-97ac-431051e774cd)
你好，我想问下论文中是对$x_i$求导，为什么代码中是对$delta$求导呢？
代码如下：
![MIG_code](https://github.com/user-attachments/assets/802ba1fd-99c3-482b-87b3-e7cd63b7438e)

**Comment by xiaosen-wang** [comment]
With $x_t = x + \delta_t$, we have that $\frac{\partial L}{\partial x_t} = \frac{\partial L}{\partial x} = \frac{\partial L}{\partial \delta_t}$. Thus, there is no difference for the gradient calculation.
